import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import mealPlannerRouter from "./meal-planner.js";
import authOtpRouter from "./auth-otp.js";
import storesRouter from "./stores.js";
import productsRouter from "./products.js";
import ordersRouter from "./orders.js";
import usersRouter from "./users.js";
import analyticsRouter from "./analytics.js";
import slotsRouter from "./slots.js";
import storeRouter from "./store.js";
import adminRouter from "./admin.js";
import paymentsRouter from "./payments.js";
import seoRouter from "./seo.js";
import storageRouter from "./storage.js";
import categoriesRouter from "./categories.js";
import onboardingRouter from "./onboarding.js";
import platformSettingsRouter from "./platform-settings.js";
import cmsRouter from "./cms.js";
import aiChatRouter from "./ai-chat.js";
import savesRouter from "./saves.js";
import siteReviewsRouter from "./site-reviews.js";
import statsRouter from "./stats.js";
import nearbyStoresRouter from "./nearby-stores.js";
import notificationsRouter from "./notifications.js";
import pickupRouter from "./pickup.js";
import stripeCheckoutRouter from "./stripe-checkout.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/auth", authOtpRouter);
router.use("/stores", storesRouter);
router.use("/products", productsRouter);
router.use("/orders", ordersRouter);
router.use("/users", usersRouter);
router.use("/slots", slotsRouter);
router.use("/store", storeRouter);
router.use("/admin", adminRouter);
router.use(analyticsRouter);
router.use(paymentsRouter);
router.use(seoRouter);
router.use(storageRouter);
router.use(categoriesRouter);
router.use("/store/onboarding", onboardingRouter);
router.use("/admin", platformSettingsRouter);
router.use("/cms", cmsRouter);
router.use("/ai", aiChatRouter);
router.use("/saves", savesRouter);
router.use("/site-reviews", siteReviewsRouter);
router.use(statsRouter);
router.use(nearbyStoresRouter);
router.use("/notifications", notificationsRouter);
router.use("/pickup", pickupRouter);
router.use(stripeCheckoutRouter);
router.use(mealPlannerRouter);

export default router;
