const palette = {
  primary: '#3FB196',
  primaryDark: '#2A7D6A',
  primaryDarker: '#1E5C4D',
  primaryLight: '#6FCBB3',
  primaryPale: '#E8F7F3',
  gold: '#D4AF37',
  goldLight: '#F5E6A3',
  warmWhite: '#FAFAF8',
  surface: '#F4F7F6',
  darkText: '#1A2E29',
  mutedText: '#5A7A72',
  white: '#FFFFFF',
  red: '#E53935',
  amber: '#F59E0B',
  blue: '#3B82F6',
  border: '#D4E8E3',
};

export const Colors = {
  light: {
    primary: palette.primary,
    primaryDark: palette.primaryDark,
    primaryDarker: palette.primaryDarker,
    primaryLight: palette.primaryLight,
    primaryPale: palette.primaryPale,
    gold: palette.gold,
    goldLight: palette.goldLight,
    background: palette.warmWhite,
    surface: palette.surface,
    card: palette.white,
    foreground: palette.darkText,
    muted: palette.surface,
    mutedForeground: palette.mutedText,
    border: palette.border,
    destructive: palette.red,
    amber: palette.amber,
    blue: palette.blue,
    tint: palette.primary,
    tabIconDefault: '#A0B4AF',
    tabIconSelected: palette.primary,
    radius: 12,
  },
  dark: {
    primary: palette.primaryLight,
    primaryDark: palette.primary,
    primaryDarker: palette.primaryDark,
    primaryLight: '#8FD9C4',
    primaryPale: '#162F29',
    gold: palette.gold,
    goldLight: '#423413',
    background: '#0F1F1C',
    surface: '#1A2E29',
    card: '#1E3632',
    foreground: '#E8F5F1',
    muted: '#1A2E29',
    mutedForeground: '#7EA89E',
    border: '#2A4A44',
    destructive: '#FF6B6B',
    amber: '#FBB040',
    blue: '#60A5FA',
    tint: palette.primaryLight,
    tabIconDefault: '#4A7A72',
    tabIconSelected: palette.primaryLight,
    radius: 12,
  },
};

export type ColorScheme = typeof Colors.light;
